version: '3.9'
services:
  frontend:
    build:
      context: .
      args:
        VUE_APP_API_BASE_URL: ${VUE_APP_API_BASE_URL:-http://localhost:5000}
    image: news-frontend:latest
    ports:
      - "8080:80"
    environment:
      - VUE_APP_API_BASE_URL=${VUE_APP_API_BASE_URL:-http://localhost:5000}
    depends_on: []
