# Use an official Python runtime as a base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Download NLTK resources in the Docker image
#RUN python -m nltk.downloader stopwords vader_lexicon punkt wordnet

EXPOSE 8000


# Copy the .env file
COPY .env /app/.env

   

# Run the Flask app module
CMD ["python", "-m", "app"]
