version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: ["python", "-m", "app"]
    volumes:
      - ./:/app
    restart: unless-stopped
